name: beamer_website
description: A website serving as a self-explanatory, in depth documentation for Beamer package

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  beamer:
    path: ../package
  url_launcher: ^6.0.20
  flutter_highlight: ^0.7.0
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true